version: v2
global:
  runner:
    os_image: ubuntu # use Linux-VM build environment to run the tasks
  variables: # environment variables to be injected into each task
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - GOFLAGS=-mod=vendor
  - LD_FLAGS=-w -s

tasks:
  setup-environment: # Setup environment
    steps:
    - checkout  # clone the git repo

    # Make binary executable
    - run: chmod +x your-binary-file

  run-titan:
    depends: [setup-environment]
    steps:
    - run: python3 titan.py
