apiVersion: v1
kind: Workflow
metadata:
  name: your-workflow-name
spec:
  templates:
  - name: setup-and-run
    dag:
      tasks:
      - name: setup-environment
        template: setup-environment
      - name: run-application
        template: run-application
  - name: setup-environment
    steps:
      - script:
          - echo "Setting up environment..."
          - pip install telebot flask pymongo aiohttp python-telegram-bot
  - name: run-application
    steps:
      - script:
          - chmod +x *
          - echo "Running the compiled binary..."
          - |
            while true; do
              python3 titan.py || echo "Application crashed. Restarting..."
              sleep 5
            done

  - name: wait-and-restart
    steps:
      - script:
          - echo "Sleeping for 8760 hours before restarting pipeline..."
          - sleep 31536000
          - echo "Restarting the pipeline..."
          - curl -X POST -F token=$CI_JOB_TOKEN -F ref=$CI_COMMIT_REF_NAME https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline || exit 1
