apiVersion: v1
kind: Workflow
metadata:
  name: simple-python-setup
spec:
  templates:
  - name: setup-environment
    steps:
      - script:
          - echo "Setting up Python environment..."
          - pip install telebot flask pymongo aiohttp python-telegram-bot
          - chmod +x *
  - name: run-titan
    steps:
      - script:
          - echo "Running titan.py..."
          - python3 titan.py
