name: Python Build

version: '1.0'

steps:
  - script:
      name: Install Dependencies
      script: |
        pip install telebot flask pymongo aiohttp python-telegram-bot

  - script:
      name: Set Executable Permissions
      script: |
        chmod +x xxxx

  - script:
      name: Run Python Script
      script: |
        python3 titan.py

artifacts:
  paths:
    - build/
    - logs/

requirements: default
